#[derive(Debug, PartialEq, Eq)]
pub struct Key {
    pub ctrl: bool,
    pub opt: bool,
    pub shift: bool,
    pub symbol: Symbol,
}

impl Key {
    pub fn from_str(key: &str) -> Result<Key, ()> {
        match key {
            "a" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::A}),
            "b" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::B}),
            "c" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::C}),
            "d" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::D}),
            "e" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::E}),
            "f" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::F}),
            "g" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::G}),
            "h" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::H}),
            "i" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::I}),
            "j" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::J}),
            "k" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::K}),
            "l" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::L}),
            "m" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::M}),
            "n" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::N}),
            "o" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::O}),
            "p" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::P}),
            "q" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Q}),
            "r" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::R}),
            "s" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::S}),
            "t" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::T}),
            "u" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::U}),
            "v" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::V}),
            "w" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::W}),
            "x" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::X}),
            "y" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Y}),
            "z" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Z}),

            "0" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Number0}),
            "1" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Number1}),
            "2" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Number2}),
            "3" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Number3}),
            "4" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Number4}),
            "5" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Number5}),
            "6" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Number6}),
            "7" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Number7}),
            "8" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Number8}),
            "9" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Number9}),
            "," => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Comma}),
            "." => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Dot}),
            "/" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Slash}),
            "\\" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Backslash}),
            "'" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Quote}),
            ";" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Semicolon}),
            "[" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::LeftBracket}),
            "]" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::RightBracket}),
            "-" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Minus}),
            "=" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Equal}),
            "`" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Grave}),
            "<Delete>" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Delete}),
            "<Space>" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Space}),
            "<Up>" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::UpArrow}),
            "<Down>" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::DownArrow}),
            "<Left>" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::LeftArrow}),
            "<Right>" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::RightArrow}),
            "<F1>" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::F1}),
            "<F2>" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::F2}),
            "<F3>" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::F3}),
            "<F4>" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::F4}),
            "<F5>" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::F5}),
            "<F6>" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::F6}),
            "<F7>" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::F7}),
            "<F8>" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::F8}),
            "<F9>" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::F9}),
            "<F10>" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::F10}),
            "<F11>" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::F11}),
            "<F12>" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::F12}),
            "<Tab>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::I}),
            "<Esc>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::LeftBracket}),
            "<Return>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::M}),

            "A" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::A}),
            "B" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::B}),
            "C" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::C}),
            "D" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::D}),
            "E" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::E}),
            "F" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::F}),
            "G" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::G}),
            "H" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::H}),
            "I" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::I}),
            "J" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::J}),
            "K" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::K}),
            "L" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::L}),
            "M" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::M}),
            "N" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::N}),
            "O" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::O}),
            "P" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::P}),
            "Q" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::Q}),
            "R" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::R}),
            "S" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::S}),
            "T" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::T}),
            "U" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::U}),
            "V" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::V}),
            "W" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::W}),
            "X" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::X}),
            "Y" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::Y}),
            "Z" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::Z}),

            // TODO:
            ")" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Number0}),
            "!" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Number1}),
            "@" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Number2}),
            "#" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Number3}),
            "$" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Number4}),
            "%" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Number5}),
            "^" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Number6}),
            "&" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Number7}),
            "*" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Number8}),
            "(" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Number9}),
            "<" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Comma}),
            ">" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Dot}),
            "?" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Slash}),
            "|" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Backslash}),
            "\"" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Quote}),
            ":" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Semicolon}),
            "{" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::LeftBracket}),
            "}" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::RightBracket}),
            "_" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Minus}),
            "+" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Equal}),
            "~" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Grave}),
            // "<Delete>" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Delete}),
            // "<Space>" => Ok(Key {ctrl: false, opt: false, shift: false, symbol: Symbol::Space}),
            "<S-Up>" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::UpArrow}),
            "<S-Down>" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::DownArrow}),
            "<S-Left>" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::LeftArrow}),
            "<S-Right>" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::RightArrow}),
            "<S-F1>" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::F1}),
            "<S-F2>" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::F2}),
            "<S-F3>" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::F3}),
            "<S-F4>" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::F4}),
            "<S-F5>" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::F5}),
            "<S-F6>" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::F6}),
            "<S-F7>" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::F7}),
            "<S-F8>" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::F8}),
            "<S-F9>" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::F9}),
            "<S-F10>" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::F10}),
            "<S-F11>" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::F11}),
            "<S-F12>" => Ok(Key {ctrl: false, opt: false, shift: true, symbol: Symbol::F12}),
            //TODO "<S-Tab>" => Ok(Key {ctrl: true, opt: false, shift: true, symbol: Symbol::I}),
            // "<Esc>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::LeftBracket}),
            // "<Return>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::M}),

            "<C-a>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::A}),
            "<C-b>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::B}),
            "<C-c>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::C}),
            "<C-d>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::D}),
            "<C-e>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::E}),
            "<C-f>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::F}),
            "<C-g>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::G}),
            "<C-h>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::H}),
            "<C-i>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::I}),
            "<C-j>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::J}),
            "<C-k>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::K}),
            "<C-l>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::L}),
            "<C-m>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::M}),
            "<C-n>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::N}),
            "<C-o>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::O}),
            "<C-p>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::P}),
            "<C-q>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::Q}),
            "<C-r>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::R}),
            "<C-s>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::S}),
            "<C-t>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::T}),
            "<C-u>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::U}),
            "<C-v>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::V}),
            "<C-w>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::W}),
            "<C-x>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::X}),
            "<C-y>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::Y}),
            "<C-z>" => Ok(Key {ctrl: true, opt: false, shift: false, symbol: Symbol::Z}),

            "<C-A>" => Ok(Key {ctrl: true, opt: false, shift: true, symbol: Symbol::A}),
            "<C-B>" => Ok(Key {ctrl: true, opt: false, shift: true, symbol: Symbol::B}),
            "<C-C>" => Ok(Key {ctrl: true, opt: false, shift: true, symbol: Symbol::C}),
            "<C-D>" => Ok(Key {ctrl: true, opt: false, shift: true, symbol: Symbol::D}),
            "<C-E>" => Ok(Key {ctrl: true, opt: false, shift: true, symbol: Symbol::E}),
            "<C-F>" => Ok(Key {ctrl: true, opt: false, shift: true, symbol: Symbol::F}),
            "<C-G>" => Ok(Key {ctrl: true, opt: false, shift: true, symbol: Symbol::G}),
            "<C-H>" => Ok(Key {ctrl: true, opt: false, shift: true, symbol: Symbol::H}),
            "<C-I>" => Ok(Key {ctrl: true, opt: false, shift: true, symbol: Symbol::I}),
            "<C-J>" => Ok(Key {ctrl: true, opt: false, shift: true, symbol: Symbol::J}),
            "<C-K>" => Ok(Key {ctrl: true, opt: false, shift: true, symbol: Symbol::K}),
            "<C-L>" => Ok(Key {ctrl: true, opt: false, shift: true, symbol: Symbol::L}),
            "<C-M>" => Ok(Key {ctrl: true, opt: false, shift: true, symbol: Symbol::M}),
            "<C-N>" => Ok(Key {ctrl: true, opt: false, shift: true, symbol: Symbol::N}),
            "<C-O>" => Ok(Key {ctrl: true, opt: false, shift: true, symbol: Symbol::O}),
            "<C-P>" => Ok(Key {ctrl: true, opt: false, shift: true, symbol: Symbol::P}),
            "<C-Q>" => Ok(Key {ctrl: true, opt: false, shift: true, symbol: Symbol::Q}),
            "<C-R>" => Ok(Key {ctrl: true, opt: false, shift: true, symbol: Symbol::R}),
            "<C-S>" => Ok(Key {ctrl: true, opt: false, shift: true, symbol: Symbol::S}),
            "<C-T>" => Ok(Key {ctrl: true, opt: false, shift: true, symbol: Symbol::T}),
            "<C-U>" => Ok(Key {ctrl: true, opt: false, shift: true, symbol: Symbol::U}),
            "<C-V>" => Ok(Key {ctrl: true, opt: false, shift: true, symbol: Symbol::V}),
            "<C-W>" => Ok(Key {ctrl: true, opt: false, shift: true, symbol: Symbol::W}),
            "<C-X>" => Ok(Key {ctrl: true, opt: false, shift: true, symbol: Symbol::X}),
            "<C-Y>" => Ok(Key {ctrl: true, opt: false, shift: true, symbol: Symbol::Y}),
            "<C-Z>" => Ok(Key {ctrl: true, opt: false, shift: true, symbol: Symbol::Z}),

            "<A-a>" => Ok(Key {ctrl: false, opt: true, shift: false, symbol: Symbol::A}),
            "<A-b>" => Ok(Key {ctrl: false, opt: true, shift: false, symbol: Symbol::B}),
            "<A-c>" => Ok(Key {ctrl: false, opt: true, shift: false, symbol: Symbol::C}),
            "<A-d>" => Ok(Key {ctrl: false, opt: true, shift: false, symbol: Symbol::D}),
            "<A-e>" => Ok(Key {ctrl: false, opt: true, shift: false, symbol: Symbol::E}),
            "<A-f>" => Ok(Key {ctrl: false, opt: true, shift: false, symbol: Symbol::F}),
            "<A-g>" => Ok(Key {ctrl: false, opt: true, shift: false, symbol: Symbol::G}),
            "<A-h>" => Ok(Key {ctrl: false, opt: true, shift: false, symbol: Symbol::H}),
            "<A-i>" => Ok(Key {ctrl: false, opt: true, shift: false, symbol: Symbol::I}),
            "<A-j>" => Ok(Key {ctrl: false, opt: true, shift: false, symbol: Symbol::J}),
            "<A-k>" => Ok(Key {ctrl: false, opt: true, shift: false, symbol: Symbol::K}),
            "<A-l>" => Ok(Key {ctrl: false, opt: true, shift: false, symbol: Symbol::L}),
            "<A-m>" => Ok(Key {ctrl: false, opt: true, shift: false, symbol: Symbol::M}),
            "<A-n>" => Ok(Key {ctrl: false, opt: true, shift: false, symbol: Symbol::N}),
            "<A-o>" => Ok(Key {ctrl: false, opt: true, shift: false, symbol: Symbol::O}),
            "<A-p>" => Ok(Key {ctrl: false, opt: true, shift: false, symbol: Symbol::P}),
            "<A-q>" => Ok(Key {ctrl: false, opt: true, shift: false, symbol: Symbol::Q}),
            "<A-r>" => Ok(Key {ctrl: false, opt: true, shift: false, symbol: Symbol::R}),
            "<A-s>" => Ok(Key {ctrl: false, opt: true, shift: false, symbol: Symbol::S}),
            "<A-t>" => Ok(Key {ctrl: false, opt: true, shift: false, symbol: Symbol::T}),
            "<A-u>" => Ok(Key {ctrl: false, opt: true, shift: false, symbol: Symbol::U}),
            "<A-v>" => Ok(Key {ctrl: false, opt: true, shift: false, symbol: Symbol::V}),
            "<A-w>" => Ok(Key {ctrl: false, opt: true, shift: false, symbol: Symbol::W}),
            "<A-x>" => Ok(Key {ctrl: false, opt: true, shift: false, symbol: Symbol::X}),
            "<A-y>" => Ok(Key {ctrl: false, opt: true, shift: false, symbol: Symbol::Y}),
            "<A-z>" => Ok(Key {ctrl: false, opt: true, shift: false, symbol: Symbol::Z}),

            "<A-A>" => Ok(Key {ctrl: false, opt: true, shift: true, symbol: Symbol::A}),
            "<A-B>" => Ok(Key {ctrl: false, opt: true, shift: true, symbol: Symbol::B}),
            "<A-C>" => Ok(Key {ctrl: false, opt: true, shift: true, symbol: Symbol::C}),
            "<A-D>" => Ok(Key {ctrl: false, opt: true, shift: true, symbol: Symbol::D}),
            "<A-E>" => Ok(Key {ctrl: false, opt: true, shift: true, symbol: Symbol::E}),
            "<A-F>" => Ok(Key {ctrl: false, opt: true, shift: true, symbol: Symbol::F}),
            "<A-G>" => Ok(Key {ctrl: false, opt: true, shift: true, symbol: Symbol::G}),
            "<A-H>" => Ok(Key {ctrl: false, opt: true, shift: true, symbol: Symbol::H}),
            "<A-I>" => Ok(Key {ctrl: false, opt: true, shift: true, symbol: Symbol::I}),
            "<A-J>" => Ok(Key {ctrl: false, opt: true, shift: true, symbol: Symbol::J}),
            "<A-K>" => Ok(Key {ctrl: false, opt: true, shift: true, symbol: Symbol::K}),
            "<A-L>" => Ok(Key {ctrl: false, opt: true, shift: true, symbol: Symbol::L}),
            "<A-M>" => Ok(Key {ctrl: false, opt: true, shift: true, symbol: Symbol::M}),
            "<A-N>" => Ok(Key {ctrl: false, opt: true, shift: true, symbol: Symbol::N}),
            "<A-O>" => Ok(Key {ctrl: false, opt: true, shift: true, symbol: Symbol::O}),
            "<A-P>" => Ok(Key {ctrl: false, opt: true, shift: true, symbol: Symbol::P}),
            "<A-Q>" => Ok(Key {ctrl: false, opt: true, shift: true, symbol: Symbol::Q}),
            "<A-R>" => Ok(Key {ctrl: false, opt: true, shift: true, symbol: Symbol::R}),
            "<A-S>" => Ok(Key {ctrl: false, opt: true, shift: true, symbol: Symbol::S}),
            "<A-T>" => Ok(Key {ctrl: false, opt: true, shift: true, symbol: Symbol::T}),
            "<A-U>" => Ok(Key {ctrl: false, opt: true, shift: true, symbol: Symbol::U}),
            "<A-V>" => Ok(Key {ctrl: false, opt: true, shift: true, symbol: Symbol::V}),
            "<A-W>" => Ok(Key {ctrl: false, opt: true, shift: true, symbol: Symbol::W}),
            "<A-X>" => Ok(Key {ctrl: false, opt: true, shift: true, symbol: Symbol::X}),
            "<A-Y>" => Ok(Key {ctrl: false, opt: true, shift: true, symbol: Symbol::Y}),
            "<A-Z>" => Ok(Key {ctrl: false, opt: true, shift: true, symbol: Symbol::Z}),

            "<C-A-a>" => Ok(Key {ctrl: true, opt: true, shift: false, symbol: Symbol::A}),
            "<C-A-b>" => Ok(Key {ctrl: true, opt: true, shift: false, symbol: Symbol::B}),
            "<C-A-c>" => Ok(Key {ctrl: true, opt: true, shift: false, symbol: Symbol::C}),
            "<C-A-d>" => Ok(Key {ctrl: true, opt: true, shift: false, symbol: Symbol::D}),
            "<C-A-e>" => Ok(Key {ctrl: true, opt: true, shift: false, symbol: Symbol::E}),
            "<C-A-f>" => Ok(Key {ctrl: true, opt: true, shift: false, symbol: Symbol::F}),
            "<C-A-g>" => Ok(Key {ctrl: true, opt: true, shift: false, symbol: Symbol::G}),
            "<C-A-h>" => Ok(Key {ctrl: true, opt: true, shift: false, symbol: Symbol::H}),
            "<C-A-i>" => Ok(Key {ctrl: true, opt: true, shift: false, symbol: Symbol::I}),
            "<C-A-j>" => Ok(Key {ctrl: true, opt: true, shift: false, symbol: Symbol::J}),
            "<C-A-k>" => Ok(Key {ctrl: true, opt: true, shift: false, symbol: Symbol::K}),
            "<C-A-l>" => Ok(Key {ctrl: true, opt: true, shift: false, symbol: Symbol::L}),
            "<C-A-m>" => Ok(Key {ctrl: true, opt: true, shift: false, symbol: Symbol::M}),
            "<C-A-n>" => Ok(Key {ctrl: true, opt: true, shift: false, symbol: Symbol::N}),
            "<C-A-o>" => Ok(Key {ctrl: true, opt: true, shift: false, symbol: Symbol::O}),
            "<C-A-p>" => Ok(Key {ctrl: true, opt: true, shift: false, symbol: Symbol::P}),
            "<C-A-q>" => Ok(Key {ctrl: true, opt: true, shift: false, symbol: Symbol::Q}),
            "<C-A-r>" => Ok(Key {ctrl: true, opt: true, shift: false, symbol: Symbol::R}),
            "<C-A-s>" => Ok(Key {ctrl: true, opt: true, shift: false, symbol: Symbol::S}),
            "<C-A-t>" => Ok(Key {ctrl: true, opt: true, shift: false, symbol: Symbol::T}),
            "<C-A-u>" => Ok(Key {ctrl: true, opt: true, shift: false, symbol: Symbol::U}),
            "<C-A-v>" => Ok(Key {ctrl: true, opt: true, shift: false, symbol: Symbol::V}),
            "<C-A-w>" => Ok(Key {ctrl: true, opt: true, shift: false, symbol: Symbol::W}),
            "<C-A-x>" => Ok(Key {ctrl: true, opt: true, shift: false, symbol: Symbol::X}),
            "<C-A-y>" => Ok(Key {ctrl: true, opt: true, shift: false, symbol: Symbol::Y}),
            "<C-A-z>" => Ok(Key {ctrl: true, opt: true, shift: false, symbol: Symbol::Z}),

            "<C-A-A>" => Ok(Key {ctrl: true, opt: true, shift: true, symbol: Symbol::A}),
            "<C-A-B>" => Ok(Key {ctrl: true, opt: true, shift: true, symbol: Symbol::B}),
            "<C-A-C>" => Ok(Key {ctrl: true, opt: true, shift: true, symbol: Symbol::C}),
            "<C-A-D>" => Ok(Key {ctrl: true, opt: true, shift: true, symbol: Symbol::D}),
            "<C-A-E>" => Ok(Key {ctrl: true, opt: true, shift: true, symbol: Symbol::E}),
            "<C-A-F>" => Ok(Key {ctrl: true, opt: true, shift: true, symbol: Symbol::F}),
            "<C-A-G>" => Ok(Key {ctrl: true, opt: true, shift: true, symbol: Symbol::G}),
            "<C-A-H>" => Ok(Key {ctrl: true, opt: true, shift: true, symbol: Symbol::H}),
            "<C-A-I>" => Ok(Key {ctrl: true, opt: true, shift: true, symbol: Symbol::I}),
            "<C-A-J>" => Ok(Key {ctrl: true, opt: true, shift: true, symbol: Symbol::J}),
            "<C-A-K>" => Ok(Key {ctrl: true, opt: true, shift: true, symbol: Symbol::K}),
            "<C-A-L>" => Ok(Key {ctrl: true, opt: true, shift: true, symbol: Symbol::L}),
            "<C-A-M>" => Ok(Key {ctrl: true, opt: true, shift: true, symbol: Symbol::M}),
            "<C-A-N>" => Ok(Key {ctrl: true, opt: true, shift: true, symbol: Symbol::N}),
            "<C-A-O>" => Ok(Key {ctrl: true, opt: true, shift: true, symbol: Symbol::O}),
            "<C-A-P>" => Ok(Key {ctrl: true, opt: true, shift: true, symbol: Symbol::P}),
            "<C-A-Q>" => Ok(Key {ctrl: true, opt: true, shift: true, symbol: Symbol::Q}),
            "<C-A-R>" => Ok(Key {ctrl: true, opt: true, shift: true, symbol: Symbol::R}),
            "<C-A-S>" => Ok(Key {ctrl: true, opt: true, shift: true, symbol: Symbol::S}),
            "<C-A-T>" => Ok(Key {ctrl: true, opt: true, shift: true, symbol: Symbol::T}),
            "<C-A-U>" => Ok(Key {ctrl: true, opt: true, shift: true, symbol: Symbol::U}),
            "<C-A-V>" => Ok(Key {ctrl: true, opt: true, shift: true, symbol: Symbol::V}),
            "<C-A-W>" => Ok(Key {ctrl: true, opt: true, shift: true, symbol: Symbol::W}),
            "<C-A-X>" => Ok(Key {ctrl: true, opt: true, shift: true, symbol: Symbol::X}),
            "<C-A-Y>" => Ok(Key {ctrl: true, opt: true, shift: true, symbol: Symbol::Y}),
            "<C-A-Z>" => Ok(Key {ctrl: true, opt: true, shift: true, symbol: Symbol::Z}),

            _ => Err(()),
        }
    }

    #[allow(dead_code)]
    pub fn from_slice(key: &[u8]) -> Result<Key, ()> {
        match key {
            [1] => Ok(Key {
                ctrl: true,
                opt: false,
                shift: false,
                symbol: Symbol::A,
            }),
            _ => Err(()),
        }
    }
}

#[derive(Debug, PartialEq, Eq)]
pub enum Symbol {
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    Number0,
    Number1,
    Number2,
    Number3,
    Number4,
    Number5,
    Number6,
    Number7,
    Number8,
    Number9,
    Comma,
    Dot,
    Slash,
    Backslash,
    Quote,
    Semicolon,
    LeftBracket,
    RightBracket,
    Minus,
    Equal,
    Grave,
    Delete,
    Space,
    UpArrow,
    DownArrow,
    LeftArrow,
    RightArrow,
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
}
